#
# Trickster 2.0 Example Configuration File - Example Prometheus Accelerator
#
# To use this, run: trickster -config /path/to/simple.prometheus.yaml
#
# This file demonstrates a basic configuration to accelerate
# Prometheus queries using Trickster. More documentation is
# available at https://github.com/trickstercache/trickster/docs/
#
# Copyright 2018 The Trickster Authors
#

frontend:
  listen_port: 9090

backends:
  victoriametrics:
    # update FQDN and Port to work in your environment
    origin_url: 'http://localhost:18481/select/0/prometheus'
    provider: 'prometheus'

metrics:
  listen_port: 8481   # available for scraping at http://<trickster>:<metrics.listen_port>/metrics

logging:
  log_level: 'info'
